# 不断追加数据到矩阵

In [5]:
import numpy as np

In [9]:
result = np.empty([0,6],dtype=int)

In [10]:
print (result)

[]


In [11]:
for i in range(10):
    #history = np.random.rand(1,6)
    history = np.random.randint(0,10,(1,6))
    #print ('squeence %d is %d',%(i,history))
    print ('squeence %d is\n'%i,history)
    result = np.row_stack((result,history))
    print ('result = \n',result)

squeence 0 is
 [[3 5 1 7 1 4]]
result = 
 [[3 5 1 7 1 4]]
squeence 1 is
 [[0 4 0 7 6 8]]
result = 
 [[3 5 1 7 1 4]
 [0 4 0 7 6 8]]
squeence 2 is
 [[9 4 7 1 3 8]]
result = 
 [[3 5 1 7 1 4]
 [0 4 0 7 6 8]
 [9 4 7 1 3 8]]
squeence 3 is
 [[2 1 0 9 0 5]]
result = 
 [[3 5 1 7 1 4]
 [0 4 0 7 6 8]
 [9 4 7 1 3 8]
 [2 1 0 9 0 5]]
squeence 4 is
 [[6 1 3 7 5 9]]
result = 
 [[3 5 1 7 1 4]
 [0 4 0 7 6 8]
 [9 4 7 1 3 8]
 [2 1 0 9 0 5]
 [6 1 3 7 5 9]]
squeence 5 is
 [[5 3 3 8 0 3]]
result = 
 [[3 5 1 7 1 4]
 [0 4 0 7 6 8]
 [9 4 7 1 3 8]
 [2 1 0 9 0 5]
 [6 1 3 7 5 9]
 [5 3 3 8 0 3]]
squeence 6 is
 [[6 5 9 3 9 9]]
result = 
 [[3 5 1 7 1 4]
 [0 4 0 7 6 8]
 [9 4 7 1 3 8]
 [2 1 0 9 0 5]
 [6 1 3 7 5 9]
 [5 3 3 8 0 3]
 [6 5 9 3 9 9]]
squeence 7 is
 [[2 0 6 0 5 9]]
result = 
 [[3 5 1 7 1 4]
 [0 4 0 7 6 8]
 [9 4 7 1 3 8]
 [2 1 0 9 0 5]
 [6 1 3 7 5 9]
 [5 3 3 8 0 3]
 [6 5 9 3 9 9]
 [2 0 6 0 5 9]]
squeence 8 is
 [[6 8 9 1 8 1]]
result = 
 [[3 5 1 7 1 4]
 [0 4 0 7 6 8]
 [9 4 7 1 3 8]
 [2 1 0 9 0 5]
 [6 1 3 7 5 9]